version: '3.3'
services:
  #odormap:
  #  build:
  #    context: ./odormap
  #  ports:
  #    - "8081:80"
  #  container_name: odormap
  cns_2019:
    build:
      context: ./cns_2019
    ports:
      - "8080:80"
    container_name: cns_2019
